# Generated by Django 2.2.5 on 2019-12-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191126_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('qualification', models.TextField()),
                ('country', models.TextField()),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
